### ISSUE TITLE
Fast JSON Input throws NoSuchMethodError in PDI 6.0

### ISSUE THREAD

**Issue by jbleuel** [graphiq-data/pdi-fastjsoninput-plugin#3]
I get this error when reading directly from a file within PDI 6.0 (it works in 5.4):

java.lang.NoSuchMethodError: org.pentaho.di.core.fileinput.FileInputList.getFile(I)Lorg/apache/commons/vfs/FileObject;

Most likely due to the Pentaho 6.0 upgrade from VFS 1.x to VFS 2.x - please see also the Kettle developer mailing list on this topic: https://groups.google.com/forum/#!topic/kettle-developers/hDBd8kkFZAY 

BTW: Thanks for this great step! :-)

**Comment by jadametz** [comment]
Thanks for making us aware, @jbleuel! Happy to see you're enjoying the step.

We haven't tested it out with 6.0 just yet but we definitely will as a result of this, hopefully much sooner than later.

**Comment by jadametz** [comment]
Thanks for looking into a fix for this issue, @tgf! We haven't had the chance to look into this yet.

We'd love to take in your contributions if you'd like to open a pull request.

**Comment by jadametz** [comment]
@jbleuel the `pentaho6` branch should solve your problem for the time being (at least in my very very brief test with PDI 6).

Question for you though; The jump from VFS to VFS2 seems to not be backward compatible with 5.4 which is what we're primarily using in-house at the moment. For plugins like this that are submitted to the Marketplace, how're you guys suggesting that we bridge the gap while supporting 5 and 6 (especially now that they're on 2 different branches)?

**Comment by tgf** [comment]
@jdametz you can specify multiple versions in your market entry, each with its own max_parent_version / min_parent_version

**Comment by jadametz** [comment]
Awesome, thanks for pointing that out, @tgf.

Both versions are now in the Marketplace as of this morning (https://github.com/pentaho/marketplace-metadata/pull/440).
