### PR TITLE
Update to Pentaho 6 with support for VFS2

### LINKED ISSUE #3: Fast JSON Input throws NoSuchMethodError in PDI 6.0
I get this error when reading directly from a file within PDI 6.0 (it works in 5.4):

java.lang.NoSuchMethodError: org.pentaho.di.core.fileinput.FileInputList.getFile(I)Lorg/apache/commons/vfs/FileObject;

Most likely due to the Pentaho 6.0 upgrade from VFS 1.x to VFS 2.x - please see also the Kettle developer mailing list on this topic: https://groups.google.com/forum/#!topic/kettle-developers/hDBd8kkFZAY 

BTW: Thanks for this great step! :-)

### PR DESCRIPTION
**Pull request by jadametz**
Update pentaho6, vfs2, deprecated; fixes #3

### CODE REVIEW

**Comment by jadametz** [comment]
Hey @tgf, we're looking to start testing PDI 6.0 very soon so I wanted to open the PR myself in order to take in your changes rather than committing them myself. Hope you don't mind!

**Comment by tgf** [comment]
don't mind at all, thanks!
